api-version: '1.14'
tests: Tests
depend:
- alles
name: TestPlugin
main: de.derteufelqwe.AutoPluginProcessor.testfiles.TestPlugin
version: '1.14'
commands:
    help2:
        description: ''
    help:
        description: ''
authors:
- Arne
- Nicht Arne
